language: node_js

node_js:
    - "0.10"

before_script:
    - npm install -g coffee-script

install:
    - "npm install"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8ba89bcbfa3dc215da8b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false